services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - APP_PORT=3005
      - DYNAMO_REGION=${DYNAMO_REGION}
      - DYNAMO_ENDPOINT=${DYNAMO_ENDPOINT}
      - DYNAMO_ACCESS_KEY=${DYNAMO_ACCESS_KEY}
      - DYNAMO_SECRET_KEY=${DYNAMO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]